# Gopkg.toml

required = [
    "golang.org/x/lint",
    "github.com/stretchr/testify"
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/lint"
